name: Rust

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
      - tests/**
  pull_request:
    paths:
      - .github/workflows/rust.yml
      - Cargo.*
      - src/**
      - tests/**
  workflow_dispatch: { }

env:
  CARGO_TERM_COLOR: always

jobs:
  Rust:
    strategy:
      fail-fast: false
      matrix:
        rust:
          # NixOS 25.05
          # OpenBSD 7.7
          - 1.86.0

        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}

      - uses: actions/checkout@v4

      - run: cargo build --verbose
        shell: bash

      - run: cargo test --verbose
        shell: bash
